services:
  weather-forecast:
    build: .
    container_name: weather-forecast
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - weather-network

  nginx:
    image: nginx:latest
    container_name: weather-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - weather-forecast
    networks:
      - weather-network

networks:
  weather-network:
    driver: bridge